server:
    port: 8080

spring:
    application:
        name: user-registration-service
    
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        url: jdbc:mysql://localhost:3306/hospitalmngsys
        username: root
        password: Akshay@2409
        driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
        defaultZone: "http://localhost:8070/eureka/" 

jwt:
    secret:
        key: eiwryctmwscigkfmushcarmfguiarsfguilwrufkafjawfgawluifaiojfaiosiodfjapjsdf

# spring.application.name=user-registration-service

# spring.datasource.url=jdbc:mysql://localhost:3306/hospitalmngsys
# spring.datasource.username=root
# spring.datasource.password=Akshay@2409
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=create

# jwt.secret.key=eiwryctmwscigkfmushcarmfguiarsfguilwrufkafjawfgawluifaiojfaiosiodfjapjsdf